### ISSUE TITLE
Deployment on pypi

### ISSUE THREAD

**Issue by nhuet** [pyrddlgym-project/pyRDDLGym-gurobi#3]
Hi, i would like to include pyRDDLGym-gurobi in the optional dependencies of our project ([sickit-decide](https://github.com/airbus/scikit-decide)).
For that we need that the dependency exists on pypi (because else we cannot ourself deploy to pypi).

Do you plan to deploy it on Pypi in the near future?

**Comment by mike-gimelfarb** [comment]
That's excellent news! I just deployed the latest version to pypi. It should be found [here](https://pypi.org/project/pyRDDLGym-gurobi/0.1/). The documentation has also just been updated. I will close the issue.

**Comment by nhuet** [comment]
Many thanks!
